spring:
  application:
    name: bot-admin-panel

  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    dateformat: 'HH:mm:ss-dd.MM.yyyy'
  file:
    name: bot-admin-panel.log

rabbitmq:
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
  connection-host: ${RABBITMQ_DOCKER_HOST}
  feedback-queue: feedback-queue
  users-statistic-queue: users-statistic-queue
  notification-queue: notification-queue

server:
  port: 8888
